/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javapoker;

import javapoker.poker.card.PokerCard;
import javapoker.poker.card.PokerSuit;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        PokerCard aceOfSpades = new PokerCard("Ace", 1, PokerSuit.SPADES);
        System.out.println(aceOfSpades);
    }
}
