/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javapoker;

import javapoker.poker.card.PokerCard;

import javapoker.poker.deck.PokerDeck;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        PokerDeck pokerDeck = new PokerDeck();
        long seed = 12345L;
        pokerDeck.shuffle(seed);
        for (PokerCard card : pokerDeck.getCards()) {
            System.out.println(card);
        }
    }
}
