/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javapoker;

import javapoker.poker.card.PokerCard;

import javapoker.poker.deck.PokerDeck;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        PokerDeck pokerDeck = new PokerDeck(12345L);
        System.out.println(pokerDeck.getRandomCard());
        pokerDeck.shuffle();
        for (PokerCard card : pokerDeck.cards()) {
            System.out.println(card);
        }
    }
}
